version: '3.8'

x-airflow-common:
  &airflow-common
  image: apache/airflow:2.8.1-python3.10
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - _PIP_ADDITIONAL_REQUIREMENTS=boto3 requests duckdb pandas pyarrow
  volumes:
    - ./dags:/opt/airflow/dags
    - ./data:/opt/airflow/data
  depends_on:
    - postgres

services:
  # Banco de dados necessário para o Airflow (Persistente)
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  # Inicializa o banco do Airflow e cria o usuário admin
  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command:
      - -c
      - |
        sleep 10
        airflow db migrate
        airflow users create --username admin --password admin --firstname Admin --lastname Admin --role Admin --email admin@example.com

  # Interface visual do Airflow
  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  # O cérebro que agenda e executa as tarefas do Airflow
  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  # Nosso Storage (O "S3 Local" - Já era persistente)
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password123
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data
  
  # Nosso Dashboard (Agora configurado para persistência)
  superset:
    image: apache/superset:3.1.2
    user: "root"
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=chave_secreta_loovi_12345
    volumes:
      - ./superset_home:/app/superset_home
    command: >
      /bin/sh -c "
      pip install duckdb-engine boto3 &&
      superset db upgrade &&
      superset fab create-admin --username admin --firstname Admin --lastname Loovi --email admin@loovi.com --password admin || true &&
      superset init &&
      gunicorn -w 2 --timeout 120 -b 0.0.0.0:8088 --limit-request-line 0 --limit-request-field_size 0 \"superset.app:create_app()\""